
package Main;

import DataProduct.Drinks.Drink;
import DataProduct.Drinks.StorageDrink;
import DataProduct.Essentials.Essentials;
import DataProduct.Essentials.StorageEss;
import DataProduct.Others.Others;
import DataProduct.Others.StorageOthers;
import DataProduct.ProcessFood.ProcessFood;
import DataProduct.ProcessFood.StorageFood;
import DataProduct.Snack.Snack;
import DataProduct.Snack.StorageSnack;
import java.awt.Cursor;
import java.awt.Window;
import javax.swing.SwingUtilities;
import raven.glasspanepopup.GlassPanePopup;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;

public class AddProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rectangleSolid1 = new Rectangle.RectangleSolid();
        l_name = new CustomFont.LabelText();
        t_name = new textfield.TextField();
        l_des = new CustomFont.LabelText();
        t_des = new textfield.TextField();
        l_cost = new CustomFont.LabelText();
        t_cost = new textfield.TextField();
        l_price = new CustomFont.LabelText();
        t_price = new textfield.TextField();
        l_cate = new CustomFont.LabelText();
        UIManager.put("ComboBox.lightweightKeyboardNavigation", false);
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);
        c_cate = new ComboBox.ComboBoxSuggestion();
        b_ok = new button.Button1();
        b_cancel = new button.ButtonClear();
        image = new UploadImage.UploadImage();

        rectangleSolid1.setRadius(65);

        l_name.setText("Product's Name");
        l_name.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_name.setBackground(new java.awt.Color(217, 217, 217));
        t_name.setForeground(new java.awt.Color(54, 54, 54));
        t_name.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        l_des.setText("Description");
        l_des.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_des.setBackground(new java.awt.Color(217, 217, 217));
        t_des.setForeground(new java.awt.Color(54, 54, 54));
        t_des.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        l_cost.setText("Cost");
        l_cost.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_cost.setBackground(new java.awt.Color(217, 217, 217));
        t_cost.setForeground(new java.awt.Color(54, 54, 54));
        t_cost.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        l_price.setText("Price");
        l_price.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_price.setBackground(new java.awt.Color(217, 217, 217));
        t_price.setForeground(new java.awt.Color(54, 54, 54));
        t_price.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        l_cate.setText("Category");
        l_cate.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        c_cate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Drinks", "Snack", "Process food", "Essentials", "Others" }));
        c_cate.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N
        c_cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cateActionPerformed(evt);
            }
        });

        b_ok.setText("OK");
        b_ok.setFont(new java.awt.Font("Afacad", 1, 22)); // NOI18N
        b_ok.setPreferredSize(new java.awt.Dimension(103, 44));
        b_ok.setRadius(35);
        b_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_okMouseEntered(evt);
            }
        });
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        b_cancel.setText("Cancel");
        b_cancel.setFont(new java.awt.Font("Afacad", 0, 22)); // NOI18N
        b_cancel.setPreferredSize(new java.awt.Dimension(103, 44));
        b_cancel.setRadius(35);
        b_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_cancelMouseEntered(evt);
            }
        });
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rectangleSolid1Layout = new javax.swing.GroupLayout(rectangleSolid1);
        rectangleSolid1.setLayout(rectangleSolid1Layout);
        rectangleSolid1Layout.setHorizontalGroup(
            rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangleSolid1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                        .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_des, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                        .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rectangleSolid1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(l_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rectangleSolid1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(l_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t_price, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_cate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        rectangleSolid1Layout.setVerticalGroup(
            rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangleSolid1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_cate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_cate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rectangleSolid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rectangleSolid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        GlassPanePopup.closePopupLast();
        
    }//GEN-LAST:event_b_cancelActionPerformed

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        if (c_cate.getSelectedItem().toString().equals("Drinks")) {
            Drink productAdd = new Drink(t_name.getText(), t_des.getText(), Double.parseDouble(t_cost.getText()), 
                    Double.parseDouble(t_price.getText()), c_cate.getSelectedItem().toString(), image.getSelectedFilePath());
            StorageDrink.addItem(productAdd);
            StorageDrink.saveToFile();
        }
        if (c_cate.getSelectedItem().toString().equals("Snack")) { 
            Snack productAdd1 = new Snack(t_name.getText(), t_des.getText(), Double.parseDouble(t_cost.getText()), 
                    Double.parseDouble(t_price.getText()), c_cate.getSelectedItem().toString(), image.getSelectedFilePath());
            StorageSnack.addItem(productAdd1);
            StorageSnack.saveToFile();
        }
        if (c_cate.getSelectedItem().toString().equals("Process food")) { 
            ProcessFood productAdd2 = new ProcessFood(t_name.getText(), t_des.getText(), Double.parseDouble(t_cost.getText()), 
                    Double.parseDouble(t_price.getText()), c_cate.getSelectedItem().toString(), image.getSelectedFilePath());
            StorageFood.addItem(productAdd2);
            StorageFood.saveToFile();
        }
        if (c_cate.getSelectedItem().toString().equals("Essentials")) { 
            Essentials productAdd4 = new Essentials(t_name.getText(), t_des.getText(), Double.parseDouble(t_cost.getText()), 
                    Double.parseDouble(t_price.getText()), c_cate.getSelectedItem().toString(), image.getSelectedFilePath());
            StorageEss.addItem(productAdd4);
            StorageEss.saveToFile();
        }
        if (c_cate.getSelectedItem().toString().equals("Others")) { 
            Others productAdd5 = new Others(t_name.getText(), t_des.getText(), Double.parseDouble(t_cost.getText()), 
                    Double.parseDouble(t_price.getText()), c_cate.getSelectedItem().toString(), image.getSelectedFilePath());
            StorageOthers.addItem(productAdd5);
            StorageOthers.saveToFile();
        }
        
        
        GlassPanePopup.closePopupLast();
        
        RunHere fr = new RunHere();
        fr.setVisible(true);
        Window w = SwingUtilities.getWindowAncestor(b_ok);
        w.dispose();
    }//GEN-LAST:event_b_okActionPerformed

    private void c_cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cateActionPerformed

    private void b_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_okMouseEntered
        b_ok.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_okMouseEntered

    private void b_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancelMouseEntered
        b_cancel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_cancelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.ButtonClear b_cancel;
    private button.Button1 b_ok;
    private ComboBox.ComboBoxSuggestion c_cate;
    private UploadImage.UploadImage image;
    private CustomFont.LabelText l_cate;
    private CustomFont.LabelText l_cost;
    private CustomFont.LabelText l_des;
    private CustomFont.LabelText l_name;
    private CustomFont.LabelText l_price;
    private Rectangle.RectangleSolid rectangleSolid1;
    private textfield.TextField t_cost;
    private textfield.TextField t_des;
    private textfield.TextField t_name;
    private textfield.TextField t_price;
    // End of variables declaration//GEN-END:variables
}
