
package Main;

import DataProduct.Drinks.StorageDrink;
import DataProduct.Essentials.StorageEss;
import DataProduct.Others.StorageOthers;
import DataProduct.ProcessFood.StorageFood;
import DataProduct.Snack.StorageSnack;
import java.awt.Cursor;
import java.awt.Window;
import javax.swing.SwingUtilities;
import raven.glasspanepopup.GlassPanePopup;
import raven.glasspanepopup.DefaultOption;
import raven.glasspanepopup.Option;

public class EditProduct extends javax.swing.JPanel {

    private String namee ;
    private String cate;
    private String des;
    private Double cost;
    private Double price;
    
    public EditProduct(String name, String des, Double costt, Double pricee, String cate) {
        this.namee = name;
        this.des = des;
        this.cate = cate;
        this.cost = costt;
        this.price = pricee;
        initComponents();
        setOpaque(false);
        t_name.setText(name);
        t_name.setEditable(false);
        t_des.setText(des);
        t_cost.setText(String.valueOf(costt));
        t_price.setText(String.valueOf(pricee));
      
    }
    
    public static void checkEditCate(String name, String des, Double cost, Double price, String cate) {
        if (cate.equals("Drinks")) {
            StorageDrink.EditData(name, des, cost, price);
            StorageDrink.saveToFile();
        }
        else if (cate.equals("Snack")) {
            StorageSnack.EditData(name, des, cost, price);
            StorageSnack.saveToFile();
        }
        else if (cate.equals("Process food")) {
            StorageFood.EditData(name, des, cost, price);
            StorageFood.saveToFile();
        }
        else if (cate.equals("Essentials")) {
            StorageEss.EditData(name, des, cost, price);
            StorageEss.saveToFile();
        }
        else if (cate.equals("Others")) {
            StorageOthers.EditData(name, des, cost, price);
            StorageOthers.saveToFile();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rectangleSolid1 = new Rectangle.RectangleSolid();
        l_name = new CustomFont.LabelText();
        t_name = new textfield.TextField();
        l_des = new CustomFont.LabelText();
        t_des = new textfield.TextField();
        l_cost = new CustomFont.LabelText();
        t_cost = new textfield.TextField();
        l_price = new CustomFont.LabelText();
        t_price = new textfield.TextField();
        b_ok = new button.Button1();
        b_cancel = new button.ButtonClear();
        b_bin = new button.ButtonNoFillNoStroke();

        rectangleSolid1.setRadius(65);

        l_name.setText("Product's Name");
        l_name.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_name.setBackground(new java.awt.Color(216, 216, 216));
        t_name.setForeground(new java.awt.Color(54, 54, 54));
        t_name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        t_name.setEnabled(false);
        t_name.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        l_des.setText("Description");
        l_des.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_des.setBackground(new java.awt.Color(217, 217, 217));
        t_des.setForeground(new java.awt.Color(54, 54, 54));
        t_des.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        l_cost.setText("Cost");
        l_cost.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_cost.setBackground(new java.awt.Color(217, 217, 217));
        t_cost.setForeground(new java.awt.Color(54, 54, 54));
        t_cost.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        l_price.setText("Price");
        l_price.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        t_price.setBackground(new java.awt.Color(217, 217, 217));
        t_price.setForeground(new java.awt.Color(54, 54, 54));
        t_price.setFont(new java.awt.Font("Afacad", 1, 18)); // NOI18N

        b_ok.setText("OK");
        b_ok.setFont(new java.awt.Font("Afacad", 1, 22)); // NOI18N
        b_ok.setPreferredSize(new java.awt.Dimension(103, 44));
        b_ok.setRadius(35);
        b_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_okMouseEntered(evt);
            }
        });
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        b_cancel.setText("Cancel");
        b_cancel.setFont(new java.awt.Font("Afacad", 0, 22)); // NOI18N
        b_cancel.setPreferredSize(new java.awt.Dimension(103, 44));
        b_cancel.setRadius(35);
        b_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_cancelMouseEntered(evt);
            }
        });
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        b_bin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin.png"))); // NOI18N
        b_bin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_binMouseEntered(evt);
            }
        });
        b_bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_binActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rectangleSolid1Layout = new javax.swing.GroupLayout(rectangleSolid1);
        rectangleSolid1.setLayout(rectangleSolid1Layout);
        rectangleSolid1Layout.setHorizontalGroup(
            rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangleSolid1Layout.createSequentialGroup()
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rectangleSolid1Layout.createSequentialGroup()
                                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(l_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rectangleSolid1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(l_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t_price, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(rectangleSolid1Layout.createSequentialGroup()
                                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b_bin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(t_des, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        rectangleSolid1Layout.setVerticalGroup(
            rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangleSolid1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rectangleSolid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_bin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rectangleSolid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rectangleSolid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        GlassPanePopup.closePopupLast();
        
    }//GEN-LAST:event_b_cancelActionPerformed

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        checkEditCate(namee, t_des.getText(), Double.valueOf(t_cost.getText()), Double.valueOf(t_price.getText()), cate);
        
        GlassPanePopup.closePopupLast();
        
        RunHere fr = new RunHere();
        fr.setVisible(true);
        Window w = SwingUtilities.getWindowAncestor(b_ok);
        w.dispose();
    }//GEN-LAST:event_b_okActionPerformed

    private void b_binActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_binActionPerformed
        Option option = new DefaultOption() {
            @Override
            public boolean closeWhenClickOutside() {
                return false;
            }
        };
        GlassPanePopup.showPopup(new PopupSure(namee, cate), option);
        
        
        
        
        
        /*checkcate(cate,namee);
        GlassPanePopup.closePopupLast();

        RunHere fr = new RunHere();
        fr.setVisible(true);
        Window w = SwingUtilities.getWindowAncestor(b_bin);
        w.dispose();*/
    }//GEN-LAST:event_b_binActionPerformed

    private void b_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_okMouseEntered
        b_ok.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_okMouseEntered

    private void b_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancelMouseEntered
        b_cancel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_cancelMouseEntered

    private void b_binMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_binMouseEntered
        b_bin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_binMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.ButtonNoFillNoStroke b_bin;
    private button.ButtonClear b_cancel;
    private button.Button1 b_ok;
    private CustomFont.LabelText l_cost;
    private CustomFont.LabelText l_des;
    private CustomFont.LabelText l_name;
    private CustomFont.LabelText l_price;
    private Rectangle.RectangleSolid rectangleSolid1;
    private textfield.TextField t_cost;
    private textfield.TextField t_des;
    private textfield.TextField t_name;
    private textfield.TextField t_price;
    // End of variables declaration//GEN-END:variables
}
