
package Main;

import java.awt.Cursor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import raven.glasspanepopup.DefaultOption;
import raven.glasspanepopup.GlassPanePopup;
import raven.glasspanepopup.Option;

public class ProductPanel extends javax.swing.JPanel {

    private String name;
    private String des;
    private Double cost1;
    private Double price1;
    private String exp;
    private String category;
    private int quantity;
    /**
     * Creates new form ProductPanel
     * @param name
     * @param des
     * @param costt
     * @param pricee
     * @param exp
     * @param cate
     * @param path
     */
    public ProductPanel(String name, String des, double costt, double pricee, int quantity, String exp, String cate, String path) {
        initComponents();
        setOpaque(false);
        l_name.setText(name);
        l_des.setText(des);
        cost.setText(String.valueOf(costt));
        price.setText(String.valueOf(pricee));
        l_date.setText(exp);
        l_image.setIcon(displayImage(path));
        l_image.setText("");
        left.setText(String.valueOf(quantity));
        this.name = name;
        this.des = des;
        this.cost1 = costt;
        this.price1 = pricee;
        this.exp = exp;
        this.category = cate;
        this.quantity = quantity;
    }
    
    private ImageIcon displayImage(String imagePath) {
        
        try {
            BufferedImage img = ImageIO.read(new File(imagePath));
            ImageIcon imageIcon = new ImageIcon(img);            
            return imageIcon;

        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rectangle1 = new Rectangle.Rectangle();
        l_name = new CustomFont.LabelText();
        l_des = new CustomFont.LabelText();
        labelText3 = new CustomFont.LabelText();
        labelText4 = new CustomFont.LabelText();
        cost = new CustomFont.LabelText();
        price = new CustomFont.LabelText();
        b_edit = new button.Button1();
        l_exp = new CustomFont.LabelText();
        l_date = new CustomFont.LabelText();
        l_left = new CustomFont.LabelText();
        left = new CustomFont.LabelText();
        l_image = new CustomFont.LabelText();

        rectangle1.setRadius(55);

        l_name.setText("Product's name");

        l_des.setText("description");
        l_des.setFont(new java.awt.Font("Afacad", 0, 16)); // NOI18N

        labelText3.setText("Cost :");
        labelText3.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        labelText4.setText("Price :");
        labelText4.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        cost.setText("0");
        cost.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        price.setText("0");
        price.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        b_edit.setText("Edit");
        b_edit.setPreferredSize(new java.awt.Dimension(56, 29));
        b_edit.setRadius(25);
        b_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_editMouseEntered(evt);
            }
        });
        b_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editActionPerformed(evt);
            }
        });

        l_exp.setText("EXP :");
        l_exp.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        l_date.setText("-");
        l_date.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        l_left.setText("left");
        l_left.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N

        left.setText("0");
        left.setFont(new java.awt.Font("Afacad", 1, 20)); // NOI18N

        l_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_image.setText("image");

        javax.swing.GroupLayout rectangle1Layout = new javax.swing.GroupLayout(rectangle1);
        rectangle1.setLayout(rectangle1Layout);
        rectangle1Layout.setHorizontalGroup(
            rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangle1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_image, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rectangle1Layout.createSequentialGroup()
                        .addComponent(l_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rectangle1Layout.createSequentialGroup()
                        .addComponent(labelText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rectangle1Layout.createSequentialGroup()
                        .addComponent(labelText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(rectangle1Layout.createSequentialGroup()
                            .addComponent(b_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(l_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(l_des, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        rectangle1Layout.setVerticalGroup(
            rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectangle1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(l_image, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rectangle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rectangle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editActionPerformed

        Option option = new DefaultOption() {
            @Override
            public boolean closeWhenClickOutside() {
                return false;
            }
        };
        GlassPanePopup.showPopup(new EditProduct(name, des, cost1, price1,category), option);
    }//GEN-LAST:event_b_editActionPerformed

    private void b_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_editMouseEntered
        b_edit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_editMouseEntered

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button1 b_edit;
    private CustomFont.LabelText cost;
    private CustomFont.LabelText l_date;
    private CustomFont.LabelText l_des;
    private CustomFont.LabelText l_exp;
    private CustomFont.LabelText l_image;
    private CustomFont.LabelText l_left;
    private CustomFont.LabelText l_name;
    private CustomFont.LabelText labelText3;
    private CustomFont.LabelText labelText4;
    private CustomFont.LabelText left;
    private CustomFont.LabelText price;
    private Rectangle.Rectangle rectangle1;
    // End of variables declaration//GEN-END:variables
}
