/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainManagement;

import button.ButtonNoFillNoStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;

/**
 *
 * @author chonticha
 */
public class MenuItem extends javax.swing.JPanel {

    /**
     * Creates new form MenuItem
     */
    public MenuItem() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_drink = new button.ButtonNoFillNoStroke();
        b_snack = new button.ButtonNoFillNoStroke();
        b_ess = new button.ButtonNoFillNoStroke();
        b_food = new button.ButtonNoFillNoStroke();
        b_others = new button.ButtonNoFillNoStroke();

        b_drink.setText("Drinks");
        b_drink.setFont(new java.awt.Font("Afacad", 0, 24)); // NOI18N
        b_drink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_drinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_drinkMouseEntered(evt);
            }
        });

        b_snack.setText("Snack");
        b_snack.setFont(new java.awt.Font("Afacad", 0, 24)); // NOI18N
        b_snack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_snackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_snackMouseEntered(evt);
            }
        });

        b_ess.setText("Essential");
        b_ess.setFont(new java.awt.Font("Afacad", 0, 24)); // NOI18N
        b_ess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_essMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_essMouseEntered(evt);
            }
        });

        b_food.setText("Process food");
        b_food.setFont(new java.awt.Font("Afacad", 0, 24)); // NOI18N
        b_food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_foodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_foodMouseEntered(evt);
            }
        });

        b_others.setText("Others");
        b_others.setFont(new java.awt.Font("Afacad", 0, 24)); // NOI18N
        b_others.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_othersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_othersMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(b_drink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(b_snack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(b_food, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(b_ess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(b_others, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_drink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_snack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_ess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_food, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_others, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_drinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_drinkMouseClicked
        handleButtonClick(b_drink);
    }//GEN-LAST:event_b_drinkMouseClicked

    private void b_snackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_snackMouseClicked
        handleButtonClick(b_snack);
    }//GEN-LAST:event_b_snackMouseClicked

    private void b_foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_foodMouseClicked
        handleButtonClick(b_food);
    }//GEN-LAST:event_b_foodMouseClicked

    private void b_essMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_essMouseClicked
        handleButtonClick(b_ess);
    }//GEN-LAST:event_b_essMouseClicked

    private void b_othersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_othersMouseClicked
        handleButtonClick(b_others);
    }//GEN-LAST:event_b_othersMouseClicked

    private void b_drinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_drinkMouseEntered
        b_drink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_drinkMouseEntered

    private void b_snackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_snackMouseEntered
        b_snack.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_snackMouseEntered

    private void b_foodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_foodMouseEntered
        b_food.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_foodMouseEntered

    private void b_essMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_essMouseEntered
        b_ess.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_essMouseEntered

    private void b_othersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_othersMouseEntered
        b_others.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_b_othersMouseEntered
    
    private ButtonNoFillNoStroke current;
    
    private void handleButtonClick(ButtonNoFillNoStroke b) {
        if (current == b) {
            b.setFont(new Font("Afacad", Font.PLAIN, 24));
            current = null;
        }
        else {
            if (current != null) {
                current.setFont(new Font("Afacad", Font.PLAIN, 24));
            }
            b.setFont(new Font("Afacad", Font.BOLD, 24));
            current = b;
        }
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.ButtonNoFillNoStroke b_drink;
    private button.ButtonNoFillNoStroke b_ess;
    private button.ButtonNoFillNoStroke b_food;
    private button.ButtonNoFillNoStroke b_others;
    private button.ButtonNoFillNoStroke b_snack;
    // End of variables declaration//GEN-END:variables
}
