/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainManagement;

/**
 *
 * @author UNS_CT
 */
public class ProductAdd extends javax.swing.JPanel {

    /**
     * Creates new form ProductAdd
     */
    public ProductAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        button12 = new button.Button1();
        buttonClear1 = new button.ButtonClear();
        textFieldNoShadow6 = new textfield.TextFieldNoShadow();
        textFieldNoShadow7 = new textfield.TextFieldNoShadow();
        textFieldNoShadow8 = new textfield.TextFieldNoShadow();
        textFieldNoShadow9 = new textfield.TextFieldNoShadow();

        setPreferredSize(new java.awt.Dimension(435, 567));

        jLabel1.setFont(new java.awt.Font("Afacad", 1, 24)); // NOI18N
        jLabel1.setText("Sell");

        jLabel2.setFont(new java.awt.Font("Afacad", 1, 24)); // NOI18N
        jLabel2.setText("Product’s Name");

        jLabel3.setFont(new java.awt.Font("Afacad", 1, 24)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Afacad", 1, 24)); // NOI18N
        jLabel4.setText("Cost");

        button12.setText("OK");
        button12.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N
        button12.setPreferredSize(new java.awt.Dimension(86, 33));
        button12.setRadius(35);
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });

        buttonClear1.setText("Delete");
        buttonClear1.setFont(new java.awt.Font("Afacad", 0, 20)); // NOI18N
        buttonClear1.setPreferredSize(new java.awt.Dimension(86, 33));
        buttonClear1.setRadius(35);
        buttonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear1ActionPerformed(evt);
            }
        });

        textFieldNoShadow6.setBackground(new java.awt.Color(217, 217, 217));
        textFieldNoShadow6.setAlignmentX(0.0F);
        textFieldNoShadow6.setAlignmentY(0.0F);
        textFieldNoShadow6.setFont(new java.awt.Font("Afacad", 0, 18)); // NOI18N
        textFieldNoShadow6.setMargin(new java.awt.Insets(0, 6, 0, 6));
        textFieldNoShadow6.setPreferredSize(new java.awt.Dimension(210, 35));
        textFieldNoShadow6.setRound(0);
        textFieldNoShadow6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoShadow6ActionPerformed(evt);
            }
        });

        textFieldNoShadow7.setBackground(new java.awt.Color(217, 217, 217));
        textFieldNoShadow7.setAlignmentX(0.0F);
        textFieldNoShadow7.setAlignmentY(0.0F);
        textFieldNoShadow7.setFont(new java.awt.Font("Afacad", 0, 18)); // NOI18N
        textFieldNoShadow7.setMargin(new java.awt.Insets(0, 6, 0, 6));
        textFieldNoShadow7.setPreferredSize(new java.awt.Dimension(210, 35));
        textFieldNoShadow7.setRound(0);
        textFieldNoShadow7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoShadow7ActionPerformed(evt);
            }
        });

        textFieldNoShadow8.setBackground(new java.awt.Color(217, 217, 217));
        textFieldNoShadow8.setAlignmentX(0.0F);
        textFieldNoShadow8.setAlignmentY(0.0F);
        textFieldNoShadow8.setFont(new java.awt.Font("Afacad", 0, 18)); // NOI18N
        textFieldNoShadow8.setMargin(new java.awt.Insets(0, 6, 0, 6));
        textFieldNoShadow8.setPreferredSize(new java.awt.Dimension(210, 35));
        textFieldNoShadow8.setRound(0);
        textFieldNoShadow8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoShadow8ActionPerformed(evt);
            }
        });

        textFieldNoShadow9.setBackground(new java.awt.Color(217, 217, 217));
        textFieldNoShadow9.setAlignmentX(0.0F);
        textFieldNoShadow9.setAlignmentY(0.0F);
        textFieldNoShadow9.setFont(new java.awt.Font("Afacad", 0, 18)); // NOI18N
        textFieldNoShadow9.setMargin(new java.awt.Insets(0, 6, 0, 6));
        textFieldNoShadow9.setPreferredSize(new java.awt.Dimension(210, 35));
        textFieldNoShadow9.setRound(0);
        textFieldNoShadow9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoShadow9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldNoShadow6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNoShadow7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNoShadow8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNoShadow9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(buttonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldNoShadow7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldNoShadow8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldNoShadow9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldNoShadow6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
         this.setVisible(false);
    }//GEN-LAST:event_button12ActionPerformed

    private void buttonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClear1ActionPerformed

    private void textFieldNoShadow6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoShadow6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoShadow6ActionPerformed

    private void textFieldNoShadow7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoShadow7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoShadow7ActionPerformed

    private void textFieldNoShadow8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoShadow8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoShadow8ActionPerformed

    private void textFieldNoShadow9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoShadow9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoShadow9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button1 button12;
    private button.ButtonClear buttonClear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private textfield.TextFieldNoShadow textFieldNoShadow6;
    private textfield.TextFieldNoShadow textFieldNoShadow7;
    private textfield.TextFieldNoShadow textFieldNoShadow8;
    private textfield.TextFieldNoShadow textFieldNoShadow9;
    // End of variables declaration//GEN-END:variables
}
